<?php
declare(strict_types=1);
require_once __DIR__.'/includes/functions.php';
require_once __DIR__.'/includes/db.php';
$richArticles = require __DIR__.'/includes/articles-v11.php';
$articles=[
 'interview-createur'=>['type'=>'Interview','title'=>'Dans le sac d’un créateur : choisir moins, tourner mieux','image'=>'images/catalog/video.webp','lead'=>'Une conversation avec un vidéaste indépendant sur la préparation d’un kit fiable et réellement adapté au tournage.','body'=>['Un bon kit commence par le scénario d’usage : durée du tournage, lumière disponible, mobilité et nombre de personnes dans l’équipe.','La location permet de tester une configuration avant d’investir. Elle évite aussi de conserver du matériel rarement utilisé.','Le créateur recommande de documenter l’état, de tester l’autonomie et les connectiques, puis de prévoir une solution de secours.'],'video'=>'https://www.youtube.com/watch?v=ekKooxaeAS8'],
 'test-nikon-z8'=>['type'=>'Test produit','title'=>'Nikon Z8 : les points à vérifier avant une location','image'=>'images/catalog/camera.webp','lead'=>'Autofocus, vidéo, autonomie et ergonomie : une grille de lecture orientée usage.','body'=>['Le Nikon Z8 combine photo haute définition et fonctions vidéo avancées. Son intérêt dépend pourtant du projet et des accessoires disponibles.','Avant la remise, vérifiez le capteur, les cartes compatibles, le nombre de batteries, les connectiques et la version du firmware.','Pour un tournage long, ajoutez une alimentation adaptée et réalisez un test d’enregistrement dans le format prévu.'],'video'=>'https://www.youtube.com/watch?v=Rn5CatbKrkM'],
 'guide-location'=>['type'=>'Guide','title'=>'Location : la checklist avant, pendant et après','image'=>'images/catalog/lens.webp','lead'=>'Une méthode simple pour sécuriser la remise et le retour du matériel.','body'=>['Avant la location, les deux parties valident l’identité, les dates, l’état photographié et les accessoires remis.','Pendant l’usage, le locataire conserve les preuves et signale immédiatement tout incident.','Au retour, les parties comparent les photos et clôturent la transaction après contrôle.'],'video'=>null],
 'reparation-circulaire'=>['type'=>'Économie circulaire','title'=>'Réparer avant de remplacer : décider avec méthode','image'=>'images/catalog/accessory.webp','lead'=>'La réparation prolonge la durée d’usage lorsque son coût et sa fiabilité restent cohérents.','body'=>['Le diagnostic doit distinguer usure esthétique, défaut fonctionnel et risque de panne.','La disponibilité des pièces, la compétence du réparateur et la valeur résiduelle orientent la décision.','Focal-Shift valorise une réparation documentée dans son indicateur interne de circularité.'],'video'=>'https://www.ifixit.com/Device/Camera']
];
$slug=(string)($_GET['slug']??'');
if (isset($richArticles[$slug])) {
    $article = $richArticles[$slug];
    $articleSlugs = array_keys($richArticles);
    $articlePosition = array_search($slug, $articleSlugs, true);
    $previousSlug = $articleSlugs[($articlePosition - 1 + count($articleSlugs)) % count($articleSlugs)];
    $nextSlug = $articleSlugs[($articlePosition + 1) % count($articleSlugs)];
    $relatedStatement = db()->prepare("SELECT e.*, c.name AS category_name, c.slug AS category_slug, u.identity_verified, (SELECT ep.url FROM equipment_photos ep WHERE ep.equipment_id=e.id ORDER BY ep.id LIMIT 1) AS image_url FROM equipment e JOIN categories c ON c.id=e.category_id JOIN users u ON u.id=e.owner_id WHERE e.status='published' AND e.category_id=:category ORDER BY e.created_at DESC LIMIT 2");
    $relatedStatement->execute(['category' => (int)$article['category_id']]);
    $relatedProducts = $relatedStatement->fetchAll();
    $pageTitle=$article['title'];$pageDescription=$article['lead'];$activePage='blog';require __DIR__.'/includes/header.php';
    ?>
    <main id="main-content"><div class="container breadcrumb"><a href="<?=url('blog.php')?>">Blog</a><span>/</span><span><?=e($article['type'])?></span></div><article class="article-page"><header class="article-header"><p class="eyebrow"><?=e($article['type'])?></p><h1><?=e($article['title'])?></h1><p><?=e($article['lead'])?></p></header><img class="article-cover" src="<?=asset($article['image'])?>" alt="Matériel photo et vidéo illustrant le guide"><div class="article-body rich-article"><?php foreach ($article['sections'] as $section): ?><section><h2><?=e($section['title'])?></h2><?php foreach ($section['paragraphs'] ?? [] as $paragraph): ?><p><?=e($paragraph)?></p><?php endforeach; ?><?php if (!empty($section['list'])): ?><ul><?php foreach ($section['list'] as $point): ?><li><?=e($point)?></li><?php endforeach; ?></ul><?php endif; ?><?php if (!empty($section['table'])): ?><div class="article-table-wrap"><table><?php foreach ($section['table'] as $rowIndex => $row): ?><tr><?php foreach ($row as $cell): ?><?php if ($rowIndex === 0): ?><th><?=e($cell)?></th><?php else: ?><td><?=e($cell)?></td><?php endif; ?><?php endforeach; ?></tr><?php endforeach; ?></table></div><?php endif; ?></section><?php endforeach; ?><section class="article-faq"><p class="eyebrow">Questions fréquentes</p><h2>FAQ</h2><?php foreach ($article['faq'] as [$question,$answer]): ?><details><summary><?=e($question)?></summary><p><?=e($answer)?></p></details><?php endforeach; ?></section><aside class="article-related"><p class="eyebrow eyebrow-light">Du conseil à l’action</p><h2>Évaluez ou trouvez le matériel cité</h2><div><a href="<?=url('simulator.php')?>">Lancer une simulation</a><a href="<?=url('catalogue-location.php?category='.(int)$article['category_id'])?>">Produits à louer concernés</a><a href="<?=url('catalogue-vente.php?category='.(int)$article['category_id'])?>">Produits à acheter concernés</a></div></aside><?php if ($relatedProducts): ?><section class="article-products"><h2>Produits liés à ce guide</h2><div class="product-grid"><?php foreach ($relatedProducts as $item): ?><?php require __DIR__.'/includes/product-card.php'; ?><?php endforeach; ?></div></section><?php endif; ?><nav class="article-navigation" aria-label="Navigation entre les articles"><a href="<?=url('article.php?slug='.$previousSlug)?>"><span>Article précédent</span><strong><?=e($richArticles[$previousSlug]['title'])?></strong></a><a href="<?=url('article.php?slug='.$nextSlug)?>"><span>Article suivant</span><strong><?=e($richArticles[$nextSlug]['title'])?></strong></a></nav></div></article></main>
    <?php require __DIR__.'/includes/footer.php'; exit;
}
$article=$articles[$slug]??null;if(!$article){http_response_code(404);exit('Article introuvable.');}
$pageTitle=$article['title'];$pageDescription=$article['lead'];$activePage='blog';require __DIR__.'/includes/header.php';
?>
<main id="main-content"><div class="container breadcrumb"><a href="<?=url('blog.php')?>">Blog</a><span>/</span><span><?=e($article['type'])?></span></div><article class="article-page"><header class="article-header"><p class="eyebrow"><?=e($article['type'])?></p><h1><?=e($article['title'])?></h1><p><?=e($article['lead'])?></p></header><img class="article-cover" src="<?=asset($article['image'])?>" alt="Illustration de l’article"><div class="article-body"><?php foreach($article['body'] as $index=>$paragraph):?><section><h2><?=['Préparer son besoin','Contrôler le matériel','Décider avec confiance'][$index]??'À retenir'?></h2><p><?=e($paragraph)?></p></section><?php endforeach;?><?php if($article['video']):?><aside class="article-video-callout"><p class="eyebrow">Ressource associée</p><h2>Voir l’entretien ou le test en vidéo</h2><p>La vidéo complète l’article avec une démonstration et un retour d’expérience.</p><a class="button" href="<?=e($article['video'])?>" target="_blank" rel="noopener">Ouvrir la vidéo YouTube ↗</a></aside><?php endif;?></div></article></main>
<?php require __DIR__.'/includes/footer.php'; ?>
