<?php
declare(strict_types=1);
require_once __DIR__.'/includes/functions.php';
$pageTitle='Blog photo et vidéo';$pageDescription='Interviews, tests produits, guides et articles pour les créateurs d’images.';$activePage='blog';require __DIR__.'/includes/header.php';
$articles=[
 ['slug'=>'guide-location-materiel-video-2026','category'=>'guides','type'=>'Guide location','title'=>'Guide 2026 : réussir la location de matériel vidéo','text'=>'Choix du kit, contrôle, budget et restitution : la méthode complète pour préparer un tournage.','image'=>'images/catalog/video.webp'],
 ['slug'=>'louer-materiel-audiovisuel-securite','category'=>'guides','type'=>'Guide propriétaires','title'=>'Louer son matériel audiovisuel en toute sécurité','text'=>'Prix, vérification, photos d’état et restitution : les bonnes pratiques pour rentabiliser son équipement.','image'=>'images/catalog/camera.webp'],
 ['slug'=>'materiel-video-debutant-2026','category'=>'guides','type'=>'Guide débutant','title'=>'Quel matériel vidéo choisir pour débuter en 2026 ?','text'=>'Un kit simple, cohérent et évolutif, construit autour de vos projets réels.','image'=>'images/catalog/camera.webp'],
 ['slug'=>'interview-createur','category'=>'interviews','type'=>'Interview','title'=>'Dans le sac d’un créateur : choisir moins, tourner mieux','text'=>'Un vidéaste indépendant partage sa méthode pour construire un kit fiable et adapté au terrain.','image'=>'images/catalog/video.webp'],
 ['slug'=>'test-nikon-z8','category'=>'tests','type'=>'Test produit','title'=>'Nikon Z8 : les points à vérifier avant une location','text'=>'Autofocus, vidéo, autonomie et ergonomie analysés avant de réserver.','image'=>'images/catalog/camera.webp'],
 ['slug'=>'guide-location','category'=>'guides','type'=>'Guide pratique','title'=>'Location : la checklist avant, pendant et après','text'=>'État, accessoires, preuves et restitution : les étapes qui sécurisent les deux parties.','image'=>'images/catalog/lens.webp'],
 ['slug'=>'reparation-circulaire','category'=>'guides','type'=>'Économie circulaire','title'=>'Réparer avant de remplacer : décider avec méthode','text'=>'Coût, disponibilité des pièces et fiabilité guident une décision documentée.','image'=>'images/catalog/accessory.webp']
];
?>
<main id="main-content">
<section class="blog-hero"><div class="container"><p class="eyebrow eyebrow-light">Le Blog Focal-Shift</p><h1>Interviews, tests et choix éclairés.</h1><p>Des retours de créateurs, des essais produits et des méthodes concrètes pour acheter, louer et entretenir du matériel premium.</p></div></section>
<section class="section"><div class="container featured-story"><div class="story-video"><img src="<?=asset('images/catalog/video.webp')?>" alt="Créateur en préparation de tournage"><span>Interview vidéo</span></div><article><p class="eyebrow">À la une · Interview</p><h2>Dans le sac d’un créateur : choisir moins, tourner mieux.</h2><p>Comment composer un kit cohérent, tester avant d’investir et prolonger la durée de vie de son matériel.</p><div class="hero-actions"><a class="button" href="<?=url('article.php?slug=interview-createur')?>">Lire l’interview</a><a class="button button-secondary" href="https://www.youtube.com/watch?v=ekKooxaeAS8" target="_blank" rel="noopener">Voir la vidéo YouTube ↗</a></div></article></div></section>
<section id="articles" class="section stories-section"><div class="container"><div class="section-heading section-heading-row"><div><p class="eyebrow">Dernières publications</p><h2>Articles et essais pour mieux décider.</h2><p class="filter-status" data-filter-status aria-live="polite"><?=count($articles)?> publications affichées</p></div><div class="blog-filters" role="group" aria-label="Filtrer les publications"><button type="button" class="is-active" data-blog-filter="all" aria-pressed="true">Tous</button><button type="button" data-blog-filter="interviews" aria-pressed="false">Interviews</button><button type="button" data-blog-filter="tests" aria-pressed="false">Tests produits</button><button type="button" data-blog-filter="guides" aria-pressed="false">Guides</button></div></div><div class="stories-grid stories-grid-rich" data-blog-grid><?php foreach($articles as $article):?><article class="story-card" data-blog-card="<?=e($article['category'])?>"><img src="<?=asset($article['image'])?>" alt=""><div><span><?=e($article['type'])?></span><h3><?=e($article['title'])?></h3><p><?=e($article['text'])?></p><a class="arrow-link" href="<?=url('article.php?slug='.$article['slug'])?>">Lire l’article <span aria-hidden="true">→</span></a></div></article><?php endforeach;?></div><p class="blog-empty" data-blog-empty hidden>Aucune publication dans cette catégorie.</p><div class="editorial-note"><strong>Des articles reliés entre eux</strong><p>Chaque guide contient une FAQ et renvoie vers les parcours de location, de vente ou de simulation concernés.</p></div></div></section>
</main>
<script src="<?=asset('js/blog.js')?>" defer></script>
<?php require __DIR__.'/includes/footer.php';?>
