<?php
declare(strict_types=1);
require_once __DIR__.'/includes/functions.php';
$pageTitle='FAQ et protection';$pageDescription='Fonctionnement, protection, incidents et priorité réparation.';$activePage='faq';require __DIR__.'/includes/header.php';
$faqs=[
['Comment se déroule une location sur Focal-Shift ?','Le locataire sélectionne une offre, vérifie l’état, le niveau d’impact et le profil du propriétaire, puis ouvre une conversation. Les deux parties conviennent des dates et des accessoires. Avant la remise, elles valident l’identité, les conditions financières et un état photographique horodaté. Au retour, un second contrôle clôture la transaction.'],
['Comment la valeur du matériel est-elle déterminée ?','Le simulateur rapproche le modèle d’un référentiel tarifaire, puis applique des coefficients liés à l’âge et à l’état déclaré. Le résultat est une aide à la décision : le propriétaire conserve la maîtrise de son prix et doit signaler toute information pouvant modifier la valeur réelle.'],
['Comment fonctionne la protection du matériel ?','La protection repose sur quatre preuves complémentaires : identité des membres, description précise de l’offre, photographies avant et après usage, et conversation rattachée à la transaction. Lorsqu’une couverture d’assurance est proposée, son plafond, sa franchise, ses exclusions et la procédure de déclaration doivent être acceptés explicitement avant le paiement.'],
['Pourquoi une caution peut-elle être demandée ?','La caution couvre un risque défini sans constituer un revenu pour le propriétaire. Une préautorisation bancaire peut réserver temporairement le montant convenu. Elle ne doit être déclenchée qu’en présence d’un incident documenté, selon un processus contradictoire et des délais annoncés.'],
['Que faire en cas de casse, perte ou désaccord ?','Prévenez immédiatement l’autre membre depuis la conversation, interrompez l’utilisation si elle peut aggraver le dommage et joignez des photos détaillées. Le dossier compare l’état de départ et de retour. Un diagnostic professionnel évalue ensuite la réparabilité et le coût avant toute décision financière.'],
['Pourquoi la réparation est-elle prioritaire ?','La réparation conserve la valeur d’usage, limite l’immobilisation et évite un remplacement prématuré. Elle est privilégiée lorsque le matériel reste sûr, que les pièces sont disponibles et que son coût demeure proportionné. Si ces conditions ne sont pas réunies, le remplacement ou l’indemnisation devient l’option responsable.'],
['Que signifient les trois niveaux d’impact ?','Impact faible, en vert et accompagné du symbole ✓, indique une combinaison favorable de proximité, réemploi et réparation ; le locataire obtient 5 % de réduction sur les frais de service. Impact moyen, en orange avec le symbole ≈, signale un équilibre perfectible sans réduction. Impact élevé, en rouge avec le symbole !, invite à comparer la distance et l’historique d’usage ; aucune réduction n’est appliquée.'],
['L’indicateur correspond-il à un bilan carbone ?','Non. Il s’agit d’un indicateur d’aide au choix construit à partir de signaux observables sur la plateforme. Il ne convertit pas ces données en kilogrammes de CO₂ et ne remplace ni une analyse de cycle de vie ni une certification environnementale indépendante.'],
['Comment protéger mes données personnelles ?','Focal-Shift limite les informations demandées à celles nécessaires au compte, à la publication et aux échanges. Ne transmettez jamais de coordonnées bancaires ou de pièce d’identité dans la messagerie. Les préférences de mesure d’audience restent accessibles depuis le pied de page.'],
];
?>
<main id="main-content"><section class="faq-hero"><div class="container narrow"><p class="eyebrow eyebrow-light">Comprendre avant d’agir</p><h1>Des règles claires pour louer en confiance.</h1><p>Fonctionnement, protection, incidents, réparation et impact : les réponses essentielles avant une transaction.</p></div></section>
<section class="section"><div class="container faq-layout"><aside><p class="eyebrow">Comment ça marche</p><ol class="how-list"><li><span>01</span>Comparer</li><li><span>02</span>Échanger</li><li><span>03</span>Documenter l’état</li><li><span>04</span>Valider les conditions</li><li><span>05</span>Réparer en priorité</li></ol><a class="button button-secondary" href="<?=url('simulator.php')?>">Tester le simulateur</a></aside><div class="faq-list"><?php foreach($faqs as $index=>$faq):?><details <?= $index===0?'open':''?> id="<?= $index===5?'reparation':''?>"><summary><?=e($faq[0])?><span aria-hidden="true">+</span></summary><p><?=e($faq[1])?></p></details><?php endforeach;?></div></div></section></main>
<?php require __DIR__.'/includes/footer.php';?>
