<?php
declare(strict_types=1);
require_once __DIR__.'/includes/db.php'; require_once __DIR__.'/includes/functions.php';
$user=require_login();$pdo=db();$transactionId=filter_input(INPUT_GET,'transaction_id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'transaction_id',FILTER_VALIDATE_INT);
$q=$pdo->prepare("SELECT tr.*,e.brand,e.model FROM transaction_requests tr JOIN equipment e ON e.id=tr.equipment_id WHERE tr.id=:id AND tr.buyer_id=:buyer AND tr.transaction_type='rental'");$q->execute(['id'=>$transactionId,'buyer'=>$user['id']]);$request=$q->fetch();
if(!$request){http_response_code(404);exit('Location introuvable.');}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_is_valid($_POST['csrf_token']??null))$errors[]='La session a expiré.';
 $condition=in_array($_POST['condition_status']??'', ['unchanged','minor_change','damage_reported'],true)?$_POST['condition_status']:'';if(!$condition)$errors[]='Indiquez l’état constaté.';
 $upload=$_FILES['return_photo']??null;$path=null;
 if(!$upload||$upload['error']!==UPLOAD_ERR_OK)$errors[]='Ajoutez une photo récente avant la restitution.';
 elseif($upload['size']>MAX_UPLOAD_BYTES)$errors[]='La photo dépasse 5 Mo.';
 else{$mime=(new finfo(FILEINFO_MIME_TYPE))->file($upload['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext)$errors[]='Format accepté : JPG, PNG ou WebP.';else{$name='return-'.bin2hex(random_bytes(10)).'.'.$ext;$target=__DIR__.'/uploads/'.$name;if(move_uploaded_file($upload['tmp_name'],$target))$path='uploads/'.$name;else $errors[]='Impossible d’enregistrer la photo.';}}
 if(!$errors&&$path){try{$ins=$pdo->prepare('INSERT INTO rental_return_inspections(transaction_request_id,submitted_by,photo_url,condition_status,notes) VALUES(:transaction,:user,:photo,:condition,:notes)');$ins->execute(['transaction'=>$transactionId,'user'=>$user['id'],'photo'=>$path,'condition'=>$condition,'notes'=>trim((string)($_POST['notes']??''))]);flash('success','État de retour enregistré. La photo servira de référence lors de la restitution.');header('Location: '.url('account.php'));exit;}catch(Throwable){$errors[]='Un état de retour a déjà été enregistré ou la base V11 doit être mise à jour.';}}
}
$pageTitle='État du produit avant restitution';$activePage='account';require __DIR__.'/includes/header.php';
?>
<main id="main-content"><section class="page-hero page-hero-compact"><div class="container narrow"><p class="eyebrow">Fin de location</p><h1>Photographiez le produit avant sa restitution.</h1><p><?=e($request['brand'].' '.$request['model'])?> · la photo doit être récente, nette et prise avant l’emballage ou la remise en main propre.</p></div></section><section class="section"><div class="container narrow"><form class="form-card" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="transaction_id" value="<?=(int)$transactionId?>"><?php if($errors):?><div class="error-summary" role="alert"><h2>Vérifiez les informations</h2><ul><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?><fieldset><legend>État avant restitution</legend><div class="field"><label for="return_photo">Photo du produit *</label><input id="return_photo" name="return_photo" type="file" accept="image/jpeg,image/png,image/webp" required><small>Photographiez le produit complet, puis toute zone présentant une évolution.</small></div><div class="field"><label for="condition_status">État constaté *</label><select id="condition_status" name="condition_status" required><option value="">Choisir</option><option value="unchanged">Identique au début de la location</option><option value="minor_change">Évolution mineure à signaler</option><option value="damage_reported">Dommage ou dysfonctionnement constaté</option></select></div><div class="field"><label for="notes">Commentaire facultatif</label><textarea id="notes" name="notes" rows="4" maxlength="800" placeholder="Décrivez uniquement l’état du produit, sans donnée personnelle."></textarea></div></fieldset><button class="button button-block" type="submit">Enregistrer l’état avant restitution</button></form></div></section></main>
<?php require __DIR__.'/includes/footer.php'; ?>
