<?php
declare(strict_types=1);
require_once __DIR__.'/includes/db.php';
require_once __DIR__.'/includes/functions.php';
$user=require_login();$pdo=db();
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT)?:filter_input(INPUT_POST,'equipment_id',FILTER_VALIDATE_INT);
$type=(string)($_GET['type']??$_POST['transaction_type']??'');
if(!$id||!in_array($type,['purchase','rental'],true)){http_response_code(400);exit('Demande invalide.');}
$q=$pdo->prepare("SELECT e.*,u.full_name,c.slug category_slug,(SELECT ep.url FROM equipment_photos ep WHERE ep.equipment_id=e.id ORDER BY ep.id LIMIT 1) image_url FROM equipment e JOIN users u ON u.id=e.owner_id JOIN categories c ON c.id=e.category_id WHERE e.id=:id AND e.status='published'");$q->execute(['id'=>$id]);$item=$q->fetch();
if(!$item){http_response_code(404);exit('Offre indisponible.');}if((int)$item['owner_id']===(int)$user['id']){http_response_code(403);exit('Vous ne pouvez pas réserver votre propre offre.');}
if($type==='purchase'&&!(bool)$item['available_for_sale']){http_response_code(400);exit('Achat non disponible.');}
if($type==='rental'&&!(bool)$item['available_for_rental']){http_response_code(400);exit('Location non disponible.');}
$periods=$pdo->prepare('SELECT start_date,end_date,reason FROM equipment_unavailability WHERE equipment_id=:id AND end_date>=CURRENT_DATE ORDER BY start_date');$periods->execute(['id'=>$id]);$unavailable=$periods->fetchAll();
$errors=[];$quote=null;$start=(string)($_POST['rental_start']??'');$end=(string)($_POST['rental_end']??'');$payment=(string)($_POST['payment_method']??'card');
if($type==='purchase'){$quote=transaction_quote($item,'purchase');}
elseif($start&&$end){try{if($start<date('Y-m-d')||$end<$start)$errors[]='Choisissez une période future cohérente.';elseif(!date_range_is_available($pdo,(int)$id,$start,$end))$errors[]='Cette période chevauche une indisponibilité ou une demande existante.';else $quote=transaction_quote($item,'rental',$start,$end);}catch(Throwable){$errors[]='Les dates saisies sont invalides.';}}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_is_valid($_POST['csrf_token']??null))$errors[]='La session a expiré.';
 if(!in_array($payment,['card','bank_transfer','split_payment'],true))$errors[]='Choisissez un moyen de paiement.';
 if($type==='rental'&&!$start)$errors[]='Choisissez les dates de location.';
 if(!isset($_POST['calculate'])&&($_POST['terms_consent']??'')!=='1')$errors[]='Vous devez accepter les conditions de la demande.';
 if(!isset($_POST['calculate'])&&!$errors&&$quote){$ins=$pdo->prepare('INSERT INTO transaction_requests(equipment_id,buyer_id,transaction_type,rental_start,rental_end,payment_method,item_amount,shipping_amount,insurance_amount,total_amount) VALUES(:equipment,:buyer,:type,:start,:end,:payment,:item,:shipping,:insurance,:total)');$ins->execute(['equipment'=>$id,'buyer'=>$user['id'],'type'=>$type,'start'=>$type==='rental'?$start:null,'end'=>$type==='rental'?$end:null,'payment'=>$payment,'item'=>$quote['item'],'shipping'=>$quote['shipping'],'insurance'=>$quote['insurance'],'total'=>$quote['total']]);flash('success',$type==='purchase'?'Votre demande d’achat a été transmise au propriétaire.':'Votre demande de location a été transmise au propriétaire.');header('Location: '.url('account.php'));exit;}
}
$pageTitle=$type==='purchase'?'Acheter '.$item['brand'].' '.$item['model']:'Louer '.$item['brand'].' '.$item['model'];$activePage='catalogue';require __DIR__.'/includes/header.php';
?>
<main id="main-content"><section class="page-hero page-hero-compact"><div class="container"><p class="eyebrow"><?=$type==='purchase'?'Achat sécurisé':'Location assurée'?></p><h1><?=e($item['brand'].' '.$item['model'])?></h1><p>Vérifiez le prix complet et transmettez votre demande au propriétaire.</p></div></section><section class="section"><div class="container checkout-grid"><form class="form-card" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="equipment_id" value="<?=(int)$id?>"><input type="hidden" name="transaction_type" value="<?=e($type)?>"><?php if($errors):?><div class="error-summary"><h2>Vérifiez votre demande</h2><ul><?php foreach($errors as $error):?><li><?=e($error)?></li><?php endforeach;?></ul></div><?php endif;?>
<?php if($type==='rental'):?><fieldset><legend>Période souhaitée</legend><div class="form-grid"><label class="field"><span>Date de début</span><input type="date" name="rental_start" min="<?=date('Y-m-d')?>" value="<?=e($start)?>" required></label><label class="field"><span>Date de fin</span><input type="date" name="rental_end" min="<?=date('Y-m-d')?>" value="<?=e($end)?>" required></label></div><button class="button button-secondary" type="submit" name="calculate" value="1">Calculer le montant</button></fieldset><div class="availability-calendar"><h2>Calendrier de disponibilité</h2><?php if(!$unavailable):?><p>Aucune indisponibilité déclarée pour les prochaines semaines.</p><?php else:?><ul><?php foreach($unavailable as $period):?><li><strong><?=date('d/m/Y',strtotime($period['start_date']))?> – <?=date('d/m/Y',strtotime($period['end_date']))?></strong><span><?=e($period['reason']?:'Indisponible')?></span></li><?php endforeach;?></ul><?php endif;?></div><?php endif;?>
<fieldset><legend>Choisissez votre paiement</legend><p class="fieldset-intro">Aucun débit n’est effectué dans cette version de démonstration.</p><div class="payment-options"><?php $paymentOptions=['card'=>['Carte bancaire','Paiement sécurisé et confirmation immédiate','CB'],'bank_transfer'=>['Virement bancaire','Coordonnées transmises après validation','↗'],'split_payment'=>['Paiement en 3 fois','Échelonnez le montant sans modifier la demande','3×']];foreach($paymentOptions as $key=>$option):?><label class="payment-option"><span class="payment-icon" aria-hidden="true"><?=e($option[2])?></span><span class="payment-copy"><strong><?=e($option[0])?></strong><small><?=e($option[1])?></small></span><input type="radio" name="payment_method" value="<?=$key?>" <?=$payment===$key?'checked':''?>></label><?php endforeach;?></div></fieldset>
<?php if($quote):?><label class="checkout-consent"><input type="checkbox" name="terms_consent" value="1" required><span>J’accepte les conditions de la demande et confirme avoir vérifié le récapitulatif.</span></label><button class="button button-block checkout-submit" type="submit"><?=$type==='purchase'?'Envoyer la demande d’achat':'Demander cette location'?></button><p class="secure-note">🔒 Demande sécurisée · aucun paiement réel à cette étape</p><?php endif;?></form><aside class="checkout-summary"><div class="summary-image"><img src="<?=e(equipment_image($item['image_url'],$item['category_slug']))?>" alt="<?=e($item['brand'].' '.$item['model'])?>"><span><?=$type==='purchase'?'Achat':'Location'?></span></div><p class="eyebrow">Votre sélection</p><h2><?=e($item['brand'].' '.$item['model'])?></h2><p class="summary-owner">Proposé par <?=e($item['full_name'])?></p><?php if($quote):?><dl><div><dt><?=$type==='rental'?'Location'.($quote['days']?' · '.$quote['days'].' jours':''):'Prix du produit'?></dt><dd><?=money($type==='rental'?(float)($quote['gross_item']??$quote['item']):(float)$quote['item'])?></dd></div><?php if($type==='rental'&&!empty($quote['discount'])):?><div class="circular-discount"><dt>Réduction indicateur vert · 5 %</dt><dd>− <?=money((float)$quote['discount'])?></dd></div><?php endif;?><div><dt>Livraison suivie</dt><dd><?=money($quote['shipping'])?></dd></div><?php if($type==='rental'):?><div><dt>Assurance location</dt><dd><?=money($quote['insurance'])?></dd></div><?php endif;?><div class="total"><dt>Total estimé</dt><dd><?=money($quote['total'])?></dd></div></dl><div class="summary-assurance"><strong>Protection incluse au parcours</strong><span>Identité, disponibilité et montant vérifiés avant confirmation.</span></div><p class="microcopy">Montants de démonstration. L’assurance et le paiement nécessitent un partenaire agréé avant lancement.</p><?php else:?><p>Sélectionnez une période pour obtenir le montant détaillé.</p><?php endif;?></aside></div></section></main>
<?php require __DIR__.'/includes/footer.php'; ?>
