<?php
declare(strict_types=1);
require_once __DIR__.'/includes/db.php';
require_once __DIR__.'/includes/functions.php';
$pdo=db();$error='';
$check=$pdo->prepare("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='contact_requests'");$check->execute();$ready=(bool)$check->fetchColumn();
if($_SERVER['REQUEST_METHOD']==='POST'&&csrf_is_valid($_POST['csrf_token']??null)&&!$ready){
 try{$pdo->exec("CREATE TABLE IF NOT EXISTS contact_requests (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,full_name VARCHAR(120) NOT NULL,email VARCHAR(160) NOT NULL,profile_type ENUM('acheteur','vendeur','partenaire','presse','autre') NOT NULL,subject VARCHAR(160) NOT NULL,message TEXT NOT NULL,consent_at DATETIME NOT NULL,status ENUM('new','in_progress','answered','archived') NOT NULL DEFAULT 'new',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_contact_status_date(status,created_at),INDEX idx_contact_email(email)) ENGINE=InnoDB");$ready=true;}catch(Throwable $e){$error='La migration a échoué : '.$e->getMessage();}
}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise à niveau V10</title><style>body{margin:0;background:#111817;color:#17201f;font:16px/1.5 system-ui}.box{width:min(calc(100% - 32px),780px);margin:55px auto;background:#fffdf8;border-radius:24px;padding:38px}h1{font:500 3rem Georgia,serif}.status{padding:16px;border-radius:12px;background:<?=$ready?'#dcebdd':'#f2e5d6'?>}.button{display:inline-flex;border:0;border-radius:999px;background:#17201f;color:white;padding:14px 22px;font-weight:800;cursor:pointer}.error{background:#fff0ed;border-left:5px solid #a43c31;padding:15px}a{color:inherit;font-weight:800}</style></head><body><main class="box"><p>FOCAL-SHIFT · VERSION 10</p><h1>Contact et nouveaux contenus</h1><div class="status"><strong><?=$ready?'La V10 est prête.':'La table des demandes de contact doit être ajoutée.'?></strong><br>La migration conserve les comptes, annonces, messages, transactions et inscriptions newsletter.</div><?php if($error):?><p class="error"><?=e($error)?></p><?php endif;?><?php if(!$ready):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="button" type="submit">Installer la V10 sans effacer mes données</button></form><?php else:?><p><a href="<?=url('index.php')?>">Ouvrir la V10 →</a></p><?php endif;?></main></body></html>
