<?php
declare(strict_types=1);
require_once __DIR__.'/includes/db.php';
require_once __DIR__.'/includes/functions.php';
$pdo=db(); $updated=false; $error='';
$column=$pdo->query("SELECT COLUMN_TYPE FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='equipment' AND column_name='status'")->fetchColumn();
$ready=is_string($column)&&str_contains($column,"'reserved'");
if($_SERVER['REQUEST_METHOD']==='POST'&&csrf_is_valid($_POST['csrf_token']??null)&&!$ready){try{$pdo->exec("ALTER TABLE equipment MODIFY status ENUM('draft','published','reserved','archived') NOT NULL DEFAULT 'draft'");$updated=true;$ready=true;}catch(Throwable $exception){$error='La migration a échoué : '.$exception->getMessage();}}
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mise à niveau Focal-Shift</title><style>body{margin:0;background:#111817;color:#17201f;font:16px/1.5 system-ui}.box{width:min(calc(100% - 32px),780px);margin:55px auto;background:#fffdf8;border-radius:24px;padding:38px}h1{font:500 3rem Georgia,serif}.status{padding:16px;border-radius:12px;background:<?=$ready?'#dcebdd':'#f2e5d6'?>}.button{display:inline-flex;border:0;border-radius:999px;background:#17201f;color:white;padding:14px 22px;font-weight:800;cursor:pointer}.error{background:#fff0ed;border-left:5px solid #a43c31;padding:15px}a{color:inherit;font-weight:800}</style></head><body><main class="box"><p>FOCAL-SHIFT · MAINTENANCE</p><h1>Gestion des annonces</h1><div class="status"><strong><?=$ready?'Le module est prêt.':'Une courte migration est nécessaire.'?></strong><br>Les annonces pourront être marquées comme réservées ou louées sans être supprimées.</div><?php if($error):?><p class="error"><?=e($error)?></p><?php endif;?><?php if(!$ready):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><button class="button" type="submit">Mettre à niveau sans effacer mes données</button></form><?php else:?><p><a href="<?=url('diagnostic.php')?>">Contrôler le diagnostic →</a></p><p><a href="<?=url('account.php')?>">Ouvrir mes annonces →</a></p><?php endif;?><p><small>Cette migration conserve tous les comptes, annonces, photos et messages existants.</small></p></main></body></html>
