<?php
declare(strict_types=1);

return [
    'Sony A7 IV' => ['type_format'=>'Hybride plein format 33 Mpx','resolution_performance'=>'Photo 33 Mpx · vidéo 4K 60p · stabilisation 5 axes','compatibility'=>'Monture Sony E · objectifs FE/E','connectivity'=>'HDMI Type A, USB-C, micro, casque, Wi-Fi, Bluetooth','power'=>'Batterie NP-FZ100 · alimentation USB-C','weight_dimensions'=>'658 g avec batterie · 131,3 × 96,4 × 79,8 mm','included_accessories'=>'2 batteries, chargeur, sangle, bouchon','highlights'=>'Autofocus temps réel, double logement SD/CFexpress Type A, écran orientable'],
    'Canon EOS R6 Mark II' => ['type_format'=>'Hybride plein format 24,2 Mpx','resolution_performance'=>'Photo 24,2 Mpx · vidéo 4K 60p suréchantillonnée · rafale 40 i/s','compatibility'=>'Monture Canon RF · objectifs RF et EF avec bague','connectivity'=>'Micro-HDMI, USB-C, micro, casque, Wi-Fi, Bluetooth','power'=>'Batterie LP-E6NH · recharge USB-C','weight_dimensions'=>'670 g avec batterie · 138,4 × 98,4 × 88,4 mm','included_accessories'=>'Batterie, chargeur, sangle, bouchon, boîte','highlights'=>'Dual Pixel CMOS AF II, stabilisation capteur, écran orientable'],
    'Nikon Z8' => ['type_format'=>'Hybride plein format empilé 45,7 Mpx','resolution_performance'=>'Photo 45,7 Mpx · vidéo 8K 60p RAW et 4K 120p','compatibility'=>'Monture Nikon Z · objectifs F avec adaptateur FTZ','connectivity'=>'HDMI Type A, USB-C, micro, casque, Wi-Fi, Bluetooth, Ethernet via adaptateur','power'=>'Batterie EN-EL15c · USB-C Power Delivery','weight_dimensions'=>'910 g avec batterie · 144 × 118,5 × 83 mm','included_accessories'=>'Batterie, chargeur USB-C, poignée, protection écran','highlights'=>'Autofocus 3D, capteur stabilisé, double logement CFexpress/SD'],
    'Sony FE 70-200mm F2.8 GM II' => ['type_format'=>'Télézoom plein format à ouverture constante f/2,8','resolution_performance'=>'Focale 70–200 mm · ouverture f/2,8 à f/22 · stabilisation optique','compatibility'=>'Monture Sony E · boîtiers APS-C et plein format','connectivity'=>'Commandes AF/MF, bague d’ouverture, limiteur de mise au point','power'=>'Aucune alimentation autonome','weight_dimensions'=>'1 045 g · Ø 88 × 200 mm','included_accessories'=>'Pare-soleil, collier de pied, bouchons, housse','highlights'=>'Quatre moteurs XD, mise au point minimale 0,4–0,82 m, tropicalisation'],
    'Canon RF 24-70mm F2.8 L' => ['type_format'=>'Zoom standard plein format à ouverture constante f/2,8','resolution_performance'=>'Focale 24–70 mm · stabilisation optique 5 stops','compatibility'=>'Monture Canon RF · boîtiers EOS R','connectivity'=>'Bague de contrôle, sélecteurs AF/MF et stabilisation','power'=>'Aucune alimentation autonome','weight_dimensions'=>'900 g · Ø 88,5 × 125,7 mm','included_accessories'=>'Pare-soleil, bouchons, housse','highlights'=>'Moteur Nano USM, traitement ASC, construction série L protégée'],
    'Sigma 24-70mm F2.8 DG DN II' => ['type_format'=>'Zoom standard plein format à ouverture constante f/2,8','resolution_performance'=>'Focale 24–70 mm · diaphragme 11 lamelles · rapport 1:2,7 au grand-angle','compatibility'=>'Monture Sony E · boîtiers plein format et APS-C','connectivity'=>'Bague d’ouverture, boutons AFL, sélecteur AF/MF','power'=>'Aucune alimentation autonome','weight_dimensions'=>'745 g · Ø 87,8 × 120,2 mm','included_accessories'=>'Pare-soleil, bouchons, étui, boîte','highlights'=>'Moteur HLA rapide, verrouillage de zoom, construction résistante'],
    'Sony FX3' => ['type_format'=>'Caméra cinéma plein format 12,1 Mpx','resolution_performance'=>'Vidéo 4K jusqu’à 120p · 10 bits 4:2:2 · plage dynamique supérieure à 15 stops','compatibility'=>'Monture Sony E · objectifs FE/E','connectivity'=>'HDMI Type A, USB-C, XLR via poignée, micro, casque, Wi-Fi','power'=>'Batterie NP-FZ100 · alimentation USB-C PD','weight_dimensions'=>'715 g avec batterie · 129,7 × 77,8 × 84,5 mm','included_accessories'=>'Poignée XLR, cage, 2 batteries, chargeur','highlights'=>'Ventilation active, autofocus temps réel, stabilisation 5 axes, S-Cinetone'],
    'Blackmagic Pocket Cinema 6K Pro' => ['type_format'=>'Caméra cinéma Super 35 de 6 144 × 3 456 pixels','resolution_performance'=>'6K jusqu’à 50p · 2,8K 120p · 13 stops de dynamique','compatibility'=>'Monture Canon EF','connectivity'=>'HDMI, USB-C, mini-XLR, micro, casque, timecode','power'=>'Batterie NP-F570 · entrée 12 V · alimentation secteur','weight_dimensions'=>'1 238 g · 180 × 123 × 112 mm','included_accessories'=>'Cage, SSD, alimentation secteur, batterie, câbles','highlights'=>'Filtres ND motorisés, écran HDR inclinable, Blackmagic RAW, double ISO natif'],
    'DJI RS 4 Pro' => ['type_format'=>'Stabilisateur 3 axes pour configuration cinéma légère','resolution_performance'=>'Charge utile 4,5 kg · verrouillage automatique des axes','compatibility'=>'Appareils hybrides et caméras compactes selon équilibrage','connectivity'=>'Bluetooth, USB-C, ports RSA/NATO, transmission DJI','power'=>'Poignée BG30 · autonomie annoncée jusqu’à 13 h','weight_dimensions'=>'Environ 1,24 kg hors poignée · pliable pour transport','included_accessories'=>'Valise, poignée, plaques, support objectif, câbles','highlights'=>'Axe roll étendu, LiDAR compatible, ActiveTrack Pro, contrôle sans fil'],
    'Aputure LS 600d Pro' => ['type_format'=>'Projecteur LED COB lumière du jour 5 600 K','resolution_performance'=>'Puissance 600 W · jusqu’à 98 500 lux à 1 m avec hyper-réflecteur','compatibility'=>'Monture Bowens pour modeleurs de lumière','connectivity'=>'DMX512, Art-Net, sACN, LumenRadio, Bluetooth Sidus Link','power'=>'Secteur ou 2 batteries V-Mount/Gold Mount haute tension','weight_dimensions'=>'Tête 5,2 kg · boîtier de contrôle 3,9 kg','included_accessories'=>'Contrôleur, câble tête, hyper-réflecteur, valise à roulettes','highlights'=>'Protection météo, effets intégrés, quatre courbes de gradation, ventilation réglable'],
    'Rode NTG5' => ['type_format'=>'Microphone canon à condensateur RF-bias','resolution_performance'=>'Réponse 20 Hz–20 kHz · directivité supercardioïde · bruit propre 10 dBA','compatibility'=>'Enregistreurs, caméras et interfaces avec entrée XLR','connectivity'=>'Sortie XLR 3 broches symétrique','power'=>'Alimentation fantôme 48 V','weight_dimensions'=>'76 g · longueur 203 mm','included_accessories'=>'Suspension, bonnette mousse, bonnette anti-vent, câble','highlights'=>'Faible bruit, résistance à l’humidité, adapté au tournage extérieur'],
    'Atomos Ninja V+' => ['type_format'=>'Moniteur-enregistreur HDR tactile 5,2 pouces','resolution_performance'=>'Écran 1 000 nits · enregistrement jusqu’en 8K 30p selon source','compatibility'=>'Caméras HDMI compatibles · SSD AtomX','connectivity'=>'HDMI 2.0 entrée/sortie, USB-C, audio 3,5 mm, port d’extension','power'=>'Batteries Sony NP-F ou alimentation secteur','weight_dimensions'=>'Environ 360 g · 151 × 91,5 × 31 mm','included_accessories'=>'Cage, 2 batteries, alimentation, support SSD','highlights'=>'ProRes RAW, outils d’exposition, LUT 3D, lecture et enregistrement HDR'],
];
